In [1]:
import torch

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tensor = torch.load('./sample.pt')

In [5]:
tensor.keys()

dict_keys(['input_ids', 'labels', 'attention_mask', 'images', 'conv_type', 'epoch', 'num_iters_per_epoch', 'iters'])

In [10]:
for key in tensor.keys():
    print(key, tensor[key].shape)

input_ids torch.Size([2, 386])
labels torch.Size([2, 386])
attention_mask torch.Size([2, 386])
images torch.Size([2, 3, 8, 224, 224])


AttributeError: 'str' object has no attribute 'shape'

In [6]:
print(tensor['input_ids'])

tensor([[    1,   835, 29950,  7889, 29901,   529, 15167, 29958, 32000, 32000,
         32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000,
         32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000,
         32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000,
          1533, 15167, 29958,   450,  4863,  3743, 29871, 29947, 16608,  4559,
         29881,   472, 29871, 29900, 29889, 29900, 29892, 29871, 29945, 29889,
         29900, 29892, 29871, 29896, 29900, 29889, 29900, 29892, 29871, 29896,
         29945, 29889, 29900, 29892, 29871, 29906, 29900, 29889, 29896, 29892,
         29871, 29906, 29945, 29889, 29896, 29892, 29871, 29941, 29900, 29889,
         29896, 29892, 29871, 29941, 29945, 29889, 29896,  6923, 29889, 12027,
          7420,   278,  7156, 29915, 29879,  6030,   297,   278,  9088, 29892,
          3704,   278,  6520,  3618,   322,   278, 12469, 29889,  2277, 29937,
          7900, 22137, 29901,  3824, 29892,   278,  

In [7]:
print(tensor['labels'])

tensor([[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -

In [8]:
print(tensor['images'])

tensor([[[[[-1.7485, -1.7485, -1.7631,  ..., -1.6901, -1.6317, -1.5587],
           [-1.7485, -1.7485, -1.7631,  ..., -1.6901, -1.6463, -1.5879],
           [-1.7485, -1.7485, -1.7631,  ..., -1.6609, -1.6609, -1.6463],
           ...,
           [-1.3397, -1.3397, -1.3251,  ..., -1.4565, -1.4419, -1.4565],
           [-1.3543, -1.3397, -1.3397,  ..., -1.4565, -1.4419, -1.4419],
           [-1.3689, -1.3397, -1.3397,  ..., -1.4565, -1.4419, -1.4419]],

          [[-1.6755, -1.6755, -1.6609,  ..., -1.6463, -1.6609, -1.6755],
           [-1.6609, -1.6609, -1.6609,  ..., -1.6609, -1.6609, -1.6755],
           [-1.6463, -1.6463, -1.6463,  ..., -1.6755, -1.6755, -1.6755],
           ...,
           [-0.9893, -1.0185, -1.0477,  ..., -1.4273, -1.4419, -1.4711],
           [-1.0039, -1.0331, -1.0477,  ..., -1.4419, -1.4711, -1.5003],
           [-1.0039, -1.0331, -1.0477,  ..., -1.4711, -1.4857, -1.5295]],

          [[-1.6755, -1.7047, -1.7339,  ..., -1.6025, -1.6025, -1.6171],
           [-1.